"""Structural Protocol interfaces for hamlet module boundaries.

These Protocols define the interfaces that each major component expects from
its collaborators. They enable static type checking without circular imports.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from hamlet.event_processing.internal_event import InternalEvent
    from hamlet.persistence.types import WorldStateData
    from hamlet.world_state.types import Agent, Project, Session, Structure, Village

__all__ = [
    "WorldStateProtocol",
    "InferenceEngineProtocol",
    "PersistenceProtocol",
    "EventQueueProtocol",
]


class WorldStateProtocol(Protocol):
    """Interface that WorldStateManager consumers depend on."""

    async def handle_event(self, event: "InternalEvent") -> None: ...
    async def get_or_create_project(self, project_id: str, project_name: str) -> "Project": ...
    async def get_or_create_session(self, session_id: str, project_id: str) -> "Session": ...
    async def get_or_create_agent(
        self, session_id: str, parent_id: "str | None" = None
    ) -> "Agent": ...
    async def update_agent(self, agent_id: str, **kwargs: Any) -> None: ...
    async def add_work_units(
        self, agent_id: str, structure_type: Any, units: int
    ) -> None: ...
    async def get_all_agents(self) -> "list[Agent]": ...
    async def get_all_structures(self) -> "list[Structure]": ...
    async def get_all_villages(self) -> "list[Village]": ...
    async def get_event_log(self, limit: int = 100) -> "list[Any]": ...
    async def get_projects(self) -> "list[Project]": ...
    async def get_agents_by_session(self, session_id: str) -> "list[Agent]": ...
    async def get_village_by_project(self, project_id: str) -> "Village | None": ...


class InferenceEngineProtocol(Protocol):
    """Interface that InferenceEngine consumers depend on."""

    async def process_event(self, event: "InternalEvent") -> None: ...
    async def tick(self) -> None: ...


class PersistenceProtocol(Protocol):
    """Interface that PersistenceFacade consumers depend on."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def load_state(self) -> "WorldStateData": ...
    async def log_event(self, event: "InternalEvent") -> None: ...
    async def queue_write(self, entity_type: str, entity_id: str, data: Any) -> None: ...


class EventQueueProtocol(Protocol):
    """Interface for an asyncio.Queue-compatible event queue."""

    async def put(self, item: Any) -> None: ...
    async def get(self) -> Any: ...
    def task_done(self) -> None: ...
